-- script-bd.sql
-- Provisiona a base MySQL utilizada pelo projeto dotnet-gs2-2025.

CREATE DATABASE IF NOT EXISTS dotnetgs2
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE dotnetgs2;

CREATE TABLE IF NOT EXISTS USERS (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS RESUMES (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL,
    original_file_name VARCHAR(255),
    extracted_text LONGTEXT,
    total_skills INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_resumes_users FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS JOB_SEARCH_AUDIT (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED,
    search_term VARCHAR(255),
    location VARCHAR(120),
    results_count INT DEFAULT 0,
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_search_user FOREIGN KEY (user_id) REFERENCES USERS(id)
);

